# Generated by Django 4.2.30 on 2026-08-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_maison', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=200)),
                ('identifiant', models.CharField(editable=False, max_length=11, unique=True)),
                ('email_m', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
