# Generated by Django 4.2.21 on 2026-08-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editeur', '0002_editeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('actualite', 'Actualité'), ('politique', 'Politique'), ('economie', 'Économie'), ('sport', 'Sport'), ('culture', 'Culture'), ('technologie', 'Technologie'), ('societe', 'Société'), ('autre', 'Autre')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='articles/pdf/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='editeur.editeur')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='editeur.maison')),
            ],
        ),
    ]
